### ISSUE TITLE
Создать приложение в котором по центру экрана будет строка ввода цифр (input)

### ISSUE THREAD

**Issue by jonkofee** [cherja/education#11]
Пользователь вводит в него 12ти значное число. После этого оно автоматически добавляется в список ниже и поле очищается. Также можно вводить числа и меньшей длины, тогда по нажатию клавиши Enter - оно добавляется в список и так же поле очищается

Что нужно реализовать:
- [x] В поле можно вводить только числа, чтобы буквы даже не вводились
- [x] При вводе 12ти значного числа добавлять в список код и очищать поле
- [x] При нажатии `Enter` добавлять код и не важно какой он длины 
- [x] Добавить кнопку очистки поля
- [x] Переделать `function saveCode(value)` чтобы элемент добавлялся в DOM через `document.createElement` и последующей вставкой через `insertBefore`. Ссылка на документацию https://developer.mozilla.org/ru/docs/DOM/document.createElement https://learn.javascript.ru/modifying-document
- [x] Чтобы при открытии страницы сразу поле ввода кода было в фокусе
- [x] Убрать подсветку инпута при клике на него
- [x] Убрать мигающую палку при вводе кода
- [x] Сделать цифры белыми
- [x] Сделать невозможным убрать фокус с инпута
- [x] По умолчанию - кнопка очистки скрыта, т.к. поле пустое и нечего стирать. Как только в поле ввода появляется хоть один символ - кнопка появляется.
- [x] Вот эту иконку нужно вставить и сделать её белым цветом         ![clear symbol-50-2](https://cloud.githubusercontent.com/assets/9060043/26142417/14972a04-3ae9-11e7-9910-037cd7cd5eac.png)
- [x] При наведении мышки на инпут не должен меняться курсор
- [x] Перенести иконку в папку `/img/icons`
- [x] Принудительная очистка инпута при загрузке страницы
- [x] Сделать иконку svg https://svgontheweb.com/ru/ вариант `Object`
- [x] Выровнять иконку

**Comment by jonkofee** [comment]
ветка `bar-code`

**Comment by jonkofee** [comment]
![mockup](https://cloud.githubusercontent.com/assets/9060043/26035068/2e5d3a58-38cf-11e7-8433-093ea82372bf.png)
Вот пример страницы

**Comment by jonkofee** [comment]
цвет `#aed7ff`

**Comment by jonkofee** [comment]
Нужно еще исправить баг
<img width="389" alt="screen shot 2017-05-15 at 15 16 12" src="https://cloud.githubusercontent.com/assets/9060043/26057233/7763ceee-3981-11e7-896f-1881f0a928cf.png">

**Comment by jonkofee** [comment]
<img width="358" alt="screen shot 2017-05-16 at 09 12 58" src="https://cloud.githubusercontent.com/assets/9060043/26092123/e01f51ba-3a17-11e7-965e-b2606e920143.png">
Цвет стал черный, нужно изменить

**Comment by jonkofee** [comment]
Баг с пустой строкой
В общем смотри, бывают такие ситуации, когда ты хочешь добавить пустую строку по нажатию `Enter`, в таком случае в функции-обработчике события `onkeypress` при выполнении условия `charCode == 13` - вызывается функция `saveCode(code.value)`, но параметр который она принимает - пустой😔 т.к. в тот момент `code.value` равно `''`, т.е. пустой строке.
Исходя из этого тебе нужно в `function saveCode(value)` в начале функции сделать проверку на пустоту переменной `value`, т.е. если `value` пустая строка, тогда не выполнять дальнейший код, т.е. не создавать новый элемент и не добавлять его в список. Вопросы?

**Comment by cherja** [comment]
```javascript
if (value = "") {
    return false;
} else {
    return true;
}
```

**Comment by cherja** [comment]
Этот код не работает,но тут же проверка сделанна?

**Comment by jonkofee** [comment]
Поверка сделана, но ты в любом случае выходишь из функции оператором `return`. Хоть строка пустая, хоть не пустая код дальше не пойдет. А тебе нужно выходить из функции только когда стразах пустая. Исправленный вариант сюда напиши

**Comment by jonkofee** [comment]
Очень круто сделал, я прям в восторге☺️
Теперь осталось доделать её.
И да, зря думаешь, что это конец проекта😁

**Comment by jonkofee** [comment]
Белым цветом не сделал

**Comment by jonkofee** [comment]
<img width="566" alt="screen shot 2017-05-17 at 14 21 34" src="https://cloud.githubusercontent.com/assets/9060043/26151587/2db72296-3b0c-11e7-9b44-de99c95c5ec4.png">
Баг🐞
Вводишь сначала текст (к примеру 5 символов), обновляешь страницу - текст есть, а кнопки нет

**Comment by cherja** [comment]
Если обновляешь страницу оно все удаляется,я не пойму о чем ты

**Comment by jonkofee** [comment]
Какой браузер?

**Comment by cherja** [comment]
хром и яндекс

**Comment by jonkofee** [comment]
у меня ска в FireFox при обновлении не очищается input

**Comment by cherja** [comment]
Это у тебя кэш))))
Что то с браузером,обновление подразумевает удаление всего)
Даже динамически Добавленных элементов

**Comment by jonkofee** [comment]
Сейчас один трюк попробую, если не поможет - то FireFox еблан!)

**Comment by jonkofee** [comment]
Получилось.
Тебе нужно отловить событие, когда страница полностью запустилась (https://learn.javascript.ru/onload-ondomcontentloaded) и там вызвать функцию `clearInput()`

**Comment by cherja** [comment]
```javascript
document.addEventListener.clearInput()
```
????

**Comment by cherja** [comment]
```javascript
document.addEventListener = function(){
  clearInput();
}
```

**Comment by jonkofee** [comment]
```javascript
document.addEventListener("DOMContentLoaded", function() {
  clearInput()
});
```

**Comment by jonkofee** [comment]
```javascript
result.clear = function(){
//bla-bla-bla
}
```

**Comment by JonKofee** [comment]
тест

**Comment by cherja** [comment]
test

**Comment by cherja** [comment]
@cherja asdasd

**Comment by JonKofee** [comment]
123

**Comment by JonKofee** [comment]
gfghj

**Comment by cherja** [comment]
```javascript
result.clear = function() {
  this.innerHTML = ''
}
```

**Comment by cherja** [comment]
Синтаксис такой?

**Comment by jonkofee** [comment]
Да, всё верно)
