### ISSUE TITLE
При наведении мышки на кнопку - не правильный курсор

### ISSUE THREAD

**Issue by jonkofee** [cherja/education#12]
И когда кнопка скрыта, а ты наводишь на её место мышку - курсор меняется, а не должен

**Comment by cherja** [comment]
```css
cursor:default;
```

**Comment by jonkofee** [comment]
Нет. Зачем писать
```css
cursor:default;
```
?
Если можно просто его удалить, а он по умолчанию `default`

**Comment by cherja** [comment]
Понял-принял.
