### ISSUE TITLE
Рефакторинг кнопки

### ISSUE THREAD

**Issue by jonkofee** [cherja/education#13]
Нужно кнопку очистки переделать на `шрифтовую иконку`. Документацию можешь найти в гугле

**Comment by cherja** [comment]
# Литература
https://webors.in.ua/podklyuchenie-shrifta-ikonok-k-stranitse-sayta-i-ispolzovanie-fontello/

**Comment by jonkofee** [comment]
измени
```html
<input type="submit" name="" value="" id="sub">
```
на
```html
<button id="sub"></button>
```

**Comment by web-crab** [comment]
просто скачай и подключи Font-awesome. 
потом вставь в `button` иконку

**Comment by jonkofee** [comment]
<img width="172" alt="screen shot 2017-05-20 at 13 55 17" src="https://cloud.githubusercontent.com/assets/9060043/26275194/046aaafc-3d64-11e7-9266-3cf4ac93af6c.png">
🐛 криво лягко

**Comment by jonkofee** [comment]
Удали лишние `fontelo`
```html
  <link rel="stylesheet" href="/css/animation.css" type="text/css" />
  <link rel="stylesheet" href="/css/fontello.css" type="text/css" />
  <link rel="stylesheet" href="/css/fontello-codes.css" type="text/css" />
  <link rel="stylesheet" href="/css/fontello-embedded.css" type="text/css" />
  <link rel="stylesheet" href="/css/fontello-ie7.css" type="text/css" />
  <link rel="stylesheet" href="/css/fontello-ie7-codes.css" type="text/css" />
```
и файлы тоже

а подключай http://fontawesome.io

**Comment by jonkofee** [comment]
Ебани маштаб в браузере и посмотри на унпут, там дохуя косяков

**Comment by cherja** [comment]
Это нужно в пикселях задать ширину???

**Comment by jonkofee** [comment]
убери `border` с родительского блока и поставь на `input`, а у кнопки сделай прозрачный фон `background: transparent`.
и у кнопки можно убрать родительский блок вообще

**Comment by jonkofee** [comment]
и обнули `padding` у кнопки, она выровняется чутка

**Comment by jonkofee** [comment]
Если навести мышку чуть правее иконки, то курсор `pointer`, а я хочу чтобы он был только на иконке. и очищать поле при клике именно на иконку
