### ISSUE TITLE
Модальные окна

### ISSUE THREAD

**Issue by jonkofee** [cherja/education#5]
[Документация](http://bootstrap-3.ru/javascript.php#modals)
И так, создай новую вкладку, назови её как хочешь. Туда добавь кнопку "О маршруте". При клике на неё должно открываться модальное окно. В это окне сделай табик с такими вкладками: "Водитель", "Машина", "Груз". В каждой из этих табиков сделай информацию, к примеру, о машине (марка, модель, вес и т.д. и т.п.). Так же с водителем (ФИО, категории, возраст и т.д. и т.п.)

**Comment by jonkofee** [comment]
1. Нет вкладки по умолчанию (активной)
2. Что за кнопка "Сохранить изменения"
3. При клике на эту кнопку ничего не происходит. А что должно? Может она вообще не нужна?
4. Измени айдишник модали на более логичный, а не `#myModal`
5. Само модальное окно `#myModal`, если верить доке, то нужно его размещать вверху `body`

> Всегда стараемся размещать модаль в HTML код в положении верхнего уровня в документе, чтобы избежать других компонентов, влияющих на внешний вид и/ или функциональность модали.

**Comment by cherja** [comment]
1.Сделал
2.Убрал кнопку
3.Убрал кнопку
4.Изменил айди.

**Comment by jonkofee** [comment]
Опять забыл добавить номер задачи, я исправил

**Comment by cherja** [comment]
5.Не пойму как правильно сделать это

**Comment by jonkofee** [comment]
Смотри вот этот коммит 5996764, я там исправил

**Comment by cherja** [comment]
Разобрался

**Comment by jonkofee** [comment]
Отлично, можно делать pull-request

**Comment by cherja** [comment]
Это ещё что такое??

**Comment by cherja** [comment]
Я понял,прочитал
