### ISSUE TITLE
Popover

### ISSUE THREAD

**Issue by jonkofee** [cherja/education#7]
[Дока](http://bootstrap-3.ru/javascript.php#popovers)
Потренируйся

**Comment by cherja** [comment]
Зависимость от плагинов
Информеры требуют подключения плагина подсказок в вашей версии Bootstrap.

Я не знаю как подключить этот плагин...

**Comment by cherja** [comment]
проблема такова,я там пытался сделать поповер и в гиде оно весит в комитах.но я не комитил,что делвть ,что бы откатиться до предыдущего пуша??
и тем более я смотрю ты уже там редактировал .
что делать??

**Comment by jonkofee** [comment]
Смотри коммит 33405d6
Там я каждому элементу задал `id` и в JS повесил на них tooltip and popover

**Comment by cherja** [comment]
Ху из ху?
 ```javascript
$(function () {
    $('#popover').popover();
    $('#atiTooltip').tooltip();
    $('#galleryTooltip').tooltip();
});
```

**Comment by jonkofee** [comment]
Посмотри как я твой коммент исправил, нажми редактировать справа вверху. Так можно код вставлять, чтобы он по-людски выглядел)))

**Comment by cherja** [comment]
### Учёба
**А йоу**
_Приветики_

1. ку
2. ку
3. куку

**Comment by jonkofee** [comment]
@Это JS)))
 ```javascript
$('#popover').popover();
$('#atiTooltip').tooltip();
$('#galleryTooltip').tooltip();
```
тут ты для popover, atiTooltip, galleryTooltip вызываешь соответствующие методы, которые и делают эти тултипы

**Comment by cherja** [comment]
ТЫ МЕНЯ В ТУПИК ЗАГНАЛ)))))

**Comment by jonkofee** [comment]
Если ты хочешь сюда вставить код, то оборачиваешь его в такую движуху ` ```javascript`и `````

**Comment by cherja** [comment]
```javascript
<div class="tab-pane" id="navigationmap"> 
`````

**Comment by cherja** [comment]
Уже понял)

**Comment by cherja** [comment]
![alt-текст](
![image](https://cloud.githubusercontent.com/assets/26221419/23922436/64bbd64a-0913-11e7-9b3a-20695ed16737.png)
 "Необязательный титул")

**Comment by cherja** [comment]
Давно заметил,если в табиках нет контента,то при переключении на табик без контента с табиком с контенто-этот контент перемещается на пустой табик

**Comment by jonkofee** [comment]
Т.к. у них нет контента, то при клике на них их контент (которого нет) не отрисовывается и остаётся старый. как ты)))

**Comment by cherja** [comment]
Та ты охуел,малой)
В вк отпишись
тут не смог скрин экрана вставить через контр v

**Comment by cherja** [comment]
Как я еще понял,что айди только один раз к одному элемнту только можно присвоить???
Потому как я присвоил айди popover следующему поповеру под названием о компании оно не работало,а как вписал поповер 1-заработало и еще этому 

```javascript
data-toggle="popover1"
```

**Comment by jonkofee** [comment]
Да, айдишник должен быть уникальным на всей странице

**Comment by jonkofee** [comment]
Смотри 6481c1b, я там в JS нашел элементы по css селектору `#navigationmap button[data-toggle="popover"]`. Это получается те две кнопки. Т.е. можно до них достучатся не только по id.

**Comment by jonkofee** [comment]
Попробуй провернуть такой трюк с тултипами)

**Comment by cherja** [comment]
До них можно достучаться по айди контейнера к содержимому,как я понимаю.
ПОПИЗДЕТЬ ПО ЭТОМУ ПОВОДУ НУЖНО...

**Comment by jonkofee** [comment]
Прочитай пока что про css селекторы и зачем они нужны
